




    paths:


  pull

jobs:
  lint-markdown:
    name: Lint markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DavidAnson/markdownlint-cli2-action@eb5ca3ab411449c66620fe7f1b3c9e10547144b0
        with:
          globs: |
            "**/*.md"
            "!.github/ISSUE_TEMPLATE"

  check-links:
    name: Check for broken links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run link checker
        # For any troubleshooting, see:
        # https://github.com/lycheeverse/lychee/blob/master/docs/TROUBLESHOOTING.md


        with:
          # user-agent: if a user agent is not specified, some websites (e.g.
          # GitHub Docs) return HTTP errors which Lychee will interpret as
          # a broken link.
          # no-progress: do not show progress bar. Recommended for
          
        
        
          
        
          # A token is used to avoid GitHub rate limiting. A personal token with
          # extra permissions is enough to be able to check public repos
          # See: https://github.com/lycheeverse/lychee#github-token
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
.github/workflows/lint-docs.yml  